#!/usr/bin/env python3
"""Append 100 new species (IDs 126-225) to data.js and create placeholder images."""

import os
import json

BASE = os.path.dirname(os.path.abspath(__file__))
DATA_JS = os.path.join(BASE, 'js', 'data.js')
IMAGES_DIR = os.path.join(BASE, 'images')

# 100 genuinely new species NOT in the existing 125
# Only truly new species - no duplicates of existing ones
NEW_SPECIES = [
  # --- Macroalgae (Seaweeds) --- 126-135
  {"commonName":"Bull Kelp","latinName":"Nereocystis luetkeana","phylum":"Ochrophyta","class":"Phaeophyceae","order":"Laminariales","habitat":"Subtidal","description":"An annual kelp that forms dense surface canopies. It has a long, hollow stipe (up to 30 m) topped with a large, spherical float supporting many long, wavy blades.","identificationTips":["Long, whip-like hollow stipe with a large bulbous float at the top","Cluster of long, flat blades (30-60 cm) growing from the float","Forms dense surface canopies visible from shore"],"color":"#5a7a30"},
  {"commonName":"Giant Kelp","latinName":"Macrocystis pyrifera","phylum":"Ochrophyta","class":"Phaeophyceae","order":"Laminariales","habitat":"Subtidal","description":"Largest and fastest-growing kelp (up to 60 cm/day). Each frond has pear-shaped floats supporting wrinkled blades. Forms extensive underwater forests.","identificationTips":["Long, branching fronds with numerous small, pear-shaped floats","Each float supports a single, wrinkled, dark brown blade","Forms dense canopy forests; washes ashore in tangled masses"],"color":"#4a6b20"},
  {"commonName":"Winged Kelp","latinName":"Alaria marginata","phylum":"Ochrophyta","class":"Phaeophyceae","order":"Laminariales","habitat":"Low intertidal","description":"A kelp with a wide, flat central midrib and thin, ruffled lateral wings. The midrib produces small reproductive blades at the base. Common on wave-exposed shores.","identificationTips":["Central thick midrib with thin, ruffled wings on each side","Olive to dark brown; up to 3 m long","Small reproductive blades cluster at the base"],"color":"#6b8e3a"},
  {"commonName":"Sea Palm","latinName":"Postelsia palmaeformis","phylum":"Ochrophyta","class":"Phaeophyceae","order":"Laminariales","habitat":"Mid intertidal","description":"Looks like a miniature palm tree growing on wave-exposed rocks. Thick, rubbery stipe topped with a cluster of long, grooved blades. Grows on the most wave-battered rocks.","identificationTips":["Palm-tree-like appearance with thick stipe and crown of blades","Grows on extreme wave-exposed rocks; stands erect in the intertidal","Olive green to brown; up to 60 cm tall"],"color":"#5a8a30"},
  {"commonName":"Rockweed","latinName":"Fucus distichus","phylum":"Ochrophyta","class":"Phaeophyceae","order":"Fucales","habitat":"High to mid intertidal","description":"Common brown alga with flattened, forked fronds and distinctive swollen, heart-shaped reproductive tips. Forms dense mats on intertidal rocks.","identificationTips":["Flattened, forked branching fronds with a prominent midrib","Swollen, yellowish, heart-shaped tips during reproduction","Leathery texture; olive-brown to dark brown; forms thick mats"],"color":"#7b8a40"},
  {"commonName":"Turkish Towel","latinName":"Chondracanthus exasperatus","phylum":"Rhodophyta","class":"Florideophyceae","order":"Gigartinales","habitat":"Low intertidal","description":"Large, thick, reddish-brown seaweed with a rough, bumpy texture resembling a towel. Covered in small, wart-like papillae. Used in skincare products.","identificationTips":["Large, thick, rubbery blade with a bumpy texture","Reddish-brown to dark purple; up to 1 m long","Found in low intertidal pools"],"color":"#8b3a3a"},
  {"commonName":"Sea Lettuce","latinName":"Ulva lactuca","phylum":"Chlorophyta","class":"Ulvophyceae","order":"Ulvales","habitat":"High to mid intertidal","description":"Bright green, thin, sheet-like alga that looks like translucent lettuce leaves. Grows attached to rocks or free-floating. Indicator of nutrient-rich waters.","identificationTips":["Thin, translucent, bright green sheets with ruffled edges","Looks like green cellophane or lettuce leaves","Often abundant in nutrient-rich areas"],"color":"#66cc33"},
  {"commonName":"Iridescent Seaweed","latinName":"Mazzaella splendens","phylum":"Rhodophyta","class":"Florideophyceae","order":"Gigartinales","habitat":"Low intertidal","description":"Beautiful red alga with broad, thin blades that shimmer with brilliant blue and purple iridescence underwater. Deep red to purple when dry.","identificationTips":["Broad, thin, oval blades with brilliant blue-purple iridescence underwater","Deep red to purple when out of water","Smooth, slippery texture; found in tidepools"],"color":"#6644aa"},
  {"commonName":"Coralline Algae","latinName":"Lithothamnion spp.","phylum":"Rhodophyta","class":"Florideophyceae","order":"Corallinales","habitat":"Low intertidal","description":"Hard, pinkish-red encrusting alga that deposits calcium carbonate, creating a rock-like crust. Forms pink patches on rocks. Important habitat builder.","identificationTips":["Hard, pink to purplish-red crust on rocks and shells","Feels rough and calcified like pink sandpaper","Forms extensive pink patches in the low intertidal"],"color":"#cc6699"},
  {"commonName":"Dead Man's Fingers","latinName":"Codium fragile","phylum":"Chlorophyta","class":"Ulvophyceae","order":"Bryopsidales","habitat":"Low intertidal","description":"Green alga with thick, spongy, cylindrical branches that look like green fingers. Feels soft and velvety. An invasive species in some areas.","identificationTips":["Thick, spongy, cylindrical green branches with a velvety texture","Branches are dark green and repeatedly forked","Feels like wet felt; often floating or attached to shells"],"color":"#339933"},

  # --- Fish: Nearshore --- 136-155
  {"commonName":"Black Rockfish","latinName":"Sebastes melanops","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Common nearshore rockfish with dark grey to black body and lighter mottling. Up to 60 cm. Found around rocky reefs and kelp beds. Important fishery species.","identificationTips":["Dark grey to black body with irregular lighter patches","Large mouth; venomous spines on head and gill covers","Often hovers motionless near rocks in schools"],"color":"#2a2a3a"},
  {"commonName":"Copper Rockfish","latinName":"Sebastes caurinus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Copper-brown rockfish with a pale lateral line and dusky blotches on the back. Up to 55 cm. Territorial and slow-moving; relies on camouflage.","identificationTips":["Copper to olive-brown body with a pale lateral line stripe","Dusky blotches on the back; large, heavy-bodied appearance","Often sits motionless on the bottom"],"color":"#8b6914"},
  {"commonName":"China Rockfish","latinName":"Sebastes nebulosus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Strikingly colored rockfish with black body covered in bright yellow speckles and bold yellow lateral line stripe. Up to 45 cm. Lives in rocky crevices.","identificationTips":["Black body with bright yellow or white speckling","Bold yellow lateral line stripe from head to tail","Often wedged deep in rocky crevices"],"color":"#1a1a2a"},
  {"commonName":"Kelp Greenling","latinName":"Hexagrammos decagrammus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Slender fish with pointed snout and distinctive blue spots and wavy lines. Males and females have different color patterns. Up to 50 cm. Common in kelp beds.","identificationTips":["Slender body with small blue spots and wavy blue lines on head","Pointed snout; males bluish-grey, females brown with golden flecks","Common around kelp and rocky reefs"],"color":"#557799"},
  {"commonName":"Lingcod","latinName":"Ophiodon elongatus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Large predator with huge mouth full of sharp teeth. Up to 1.5 m. Brown to blue-green, mottled. Despite its name, not a true cod. Prized game fish.","identificationTips":["Large, elongated body with massive mouth full of sharp teeth","Mottled brown to blue-green; flesh may be blue-green","Powerful ambush predator"],"color":"#556b55"},
  {"commonName":"Cabezon","latinName":"Scorpaenichthys marmoratus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Large, bulky sculpin with broad head and thick lips. Up to 1 m. Highly variable color. The roe is toxic to humans. Powerful ambush predator.","identificationTips":["Large, broad, flattened head with fleshy eyebrows","No scales; skin is smooth with fleshy flaps","Roe contains a potent toxin — do not eat"],"color":"#7a5a4a"},
  {"commonName":"Tidepool Sculpin","latinName":"Oligocottus maculosus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"High to mid intertidal","description":"Small, well-camouflaged sculpin (up to 8 cm). Can change color to match background. Survives out of water for hours if kept moist. Very common in tidepools.","identificationTips":["Small, mottled brown sculpin with large head and tapering body","Can change color rapidly to match substrate","Often found darting around tidepools"],"color":"#8b7355"},
  {"commonName":"Buffalo Sculpin","latinName":"Enophrys bison","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Low intertidal","description":"Medium sculpin (up to 25 cm) with large head and long, sharp cheek spines resembling buffalo horns. Well camouflaged on rocky bottoms.","identificationTips":["Large, bony head with long, sharp spine on each cheek like buffalo horns","Mottled greenish-brown to grey with dark bars","Found resting on the bottom in tidepools"],"color":"#6b8e5a"},
  {"commonName":"Penpoint Gunnel","latinName":"Apodichthys flavidus","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Mid to low intertidal","description":"Slender, eel-like fish (up to 45 cm), bright green to yellow-green. Distinctive dark spot at base of tail fin. Common among algae and under rocks.","identificationTips":["Slender, eel-like body; bright green to yellow-green","Dark spot at base of caudal (tail) fin","Often coiled under rocks or in algae"],"color":"#66aa33"},
  {"commonName":"Crescent Gunnel","latinName":"Pholis laeta","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Mid intertidal","description":"Small eel-like fish (up to 20 cm) with row of dark crescent-shaped markings along the back. Olive to brown. Common under rocks and in eelgrass.","identificationTips":["Dark crescent-shaped markings along the dorsal surface","Olive to brown eel-like body with small pointed head","Found under rocks and in eelgrass beds"],"color":"#8b8640"},
  {"commonName":"High Cockscomb","latinName":"Anoplarchus purpurescens","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Mid intertidal","description":"Prickleback (up to 25 cm) with a high, fleshy crest on top of head (more prominent in males). Dark purple-brown. Found under intertidal rocks.","identificationTips":["High, fleshy crest on top of head (more prominent in males)","Elongated, eel-like body with long dorsal fin","Dark purple-brown; found under rocks"],"color":"#5a3a6a"},
  {"commonName":"Starry Flounder","latinName":"Platichthys stellatus","phylum":"Chordata","class":"Actinopterygii","order":"Pleuronectiformes","habitat":"Subtidal","description":"Large flat flounder (up to 90 cm) with both eyes usually on left side. Distinctive alternating orange and black bands on fins. Rough, star-shaped scales.","identificationTips":["Flat, oval body with both eyes on one side (usually left)","Alternating orange and dark bands on dorsal and anal fins","Rough, star-shaped scale tubercles on body"],"color":"#6b5a4a"},
  {"commonName":"Shiner Perch","latinName":"Cymatogaster aggregata","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Subtidal","description":"Small, silvery perch (up to 20 cm) with faint golden vertical bars and deeply forked tail. Lives in large schools around docks. Females give live birth.","identificationTips":["Small, silvery fish with 3-4 faint golden vertical bars","Deeply forked tail fin; small upturned mouth","Forms large dense schools around docks in summer"],"color":"#c0c8d0"},
  {"commonName":"Pacific Herring","latinName":"Clupea pallasii","phylum":"Chordata","class":"Actinopterygii","order":"Clupeiformes","habitat":"Subtidal","description":"Small, silvery schooling fish (up to 30 cm) — a keystone species. Deeply forked tail, no lateral line. Massive spring spawns turn the water milky white.","identificationTips":["Small, slender, silvery fish with bluish-green back","Deeply forked tail; large, easily shed scales","No lateral line; spawns in massive schools turning water milky"],"color":"#a0b8d0"},
  {"commonName":"Threespine Stickleback","latinName":"Gasterosteus aculeatus","phylum":"Chordata","class":"Actinopterygii","order":"Gasterosteiformes","habitat":"Low intertidal","description":"Tiny fish (up to 8 cm) with 3 sharp dorsal spines and bony plates on sides. Males develop brilliant red throat during breeding. Famous model organism in behavioral studies.","identificationTips":["3 sharp, isolated dorsal spines before the dorsal fin","Bony plates (scutes) along sides instead of scales","Breeding males have bright red-orange throat"],"color":"#88aacc"},
  {"commonName":"Northern Clingfish","latinName":"Gobiesox maeandricus","phylum":"Chordata","class":"Actinopterygii","order":"Gobiesociformes","habitat":"Mid to low intertidal","description":"Unusual fish (up to 15 cm) with large suction-cup disc on belly formed by fused pelvic fins. Clings tightly to rocks even in heavy wave action.","identificationTips":["Large suction disc (modified pelvic fins) on belly","Flattened, tadpole-shaped body with broad, rounded head","Clinging fiercely to rocks even in strong currents"],"color":"#7a6a4a"},
  {"commonName":"Pile Perch","latinName":"Rhacochilus vacca","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Subtidal","description":"Large, deep-bodied surfperch (up to 45 cm) with prominent dark spot at front base of dorsal fin. Silvery with dark vertical bars. Common around docks.","identificationTips":["Large, deep compressed body with dark spot on dorsal fin","Silvery with dark vertical bars; large eyes","Found near docks, pilings, and rocky areas"],"color":"#b0b8c0"},
  {"commonName":"Wolf Eel","latinName":"Anarrhichthys ocellatus","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Subtidal","description":"Not a true eel! Extremely long fish (up to 2.4 m) with powerful crushing teeth. Juveniles bright orange; adults grey-brown. Mated pairs share rocky dens.","identificationTips":["Extremely long, eel-like body with large head and powerful jaws","Juveniles are bright orange; adults grey to brown","Crushing teeth; lives in rocky dens, often in pairs"],"color":"#5a5a6a"},
  {"commonName":"Grunt Sculpin","latinName":"Rhamphocottus richardsonii","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Low intertidal","description":"Tiny, comical fish (up to 8 cm) with disproportionately large head and pig-like snout. It grunts! Often hides in empty giant barnacle shells.","identificationTips":["Huge head with pointed, pig-like snout and tiny body","Grunt-like sound produced when removed from water","Often hides inside empty giant barnacle shells"],"color":"#cc8877"},

  # --- More Nudibranchs & Gastropods --- 156-163
  {"commonName":"Clown Nudibranch","latinName":"Triopha catalinae","phylum":"Mollusca","class":"Gastropoda","order":"Nudibranchia","habitat":"Low intertidal","description":"Striking nudibranch (up to 9 cm) with translucent white body covered in bright orange-tipped bumps. Orange rhinophores and gill plume. Feeds on bryozoans.","identificationTips":["Translucent white body with bright orange-tipped bumps","Orange rhinophores and feathery gill plume at rear","Found on bryozoans, its primary food source"],"color":"#ff7722"},
  {"commonName":"Shaggy Mouse Nudibranch","latinName":"Aeolidia papillosa","phylum":"Mollusca","class":"Gastropoda","order":"Nudibranchia","habitat":"Low intertidal","description":"Large, greyish-brown nudibranch (up to 12 cm) covered in flattened cerata tipped with white. Looks like a shaggy mouse. Feeds almost exclusively on anemones.","identificationTips":["Dense covering of grey-brown, flattened cerata with white tips","Looks like a shaggy carpet or grey mouse","Feeds on anemones; stores stinging cells in cerata"],"color":"#8b8378"},
  {"commonName":"Leopard Nudibranch","latinName":"Diaulula sandiegensis","phylum":"Mollusca","class":"Gastropoda","order":"Nudibranchia","habitat":"Low intertidal","description":"Medium dorid (up to 8 cm) with cream body covered in dark brown ring-shaped spots — like a leopard coat. Feeds on sponges. Has distinct odor.","identificationTips":["Cream to white body with dark brown ring-shaped spots","Oval, flattened shape with ring of gills at rear","Feeds on sponges; distinctive chemical odor"],"color":"#d4c8a0"},
  {"commonName":"Giant Nudibranch","latinName":"Dendronotus iris","phylum":"Mollusca","class":"Gastropoda","order":"Nudibranchia","habitat":"Low intertidal","description":"Large nudibranch (up to 30 cm) with branching, tree-like cerata. Color varies: grey, orange, or reddish. Feeds on tube-dwelling anemones.","identificationTips":["Very large size (up to 30 cm); body covered in branched cerata","Color varies from grey to orange to red","Feeds on tube-dwelling anemones; sandy/muddy substrates"],"color":"#cc8844"},
  {"commonName":"Lined Chiton","latinName":"Tonicella lineata","phylum":"Mollusca","class":"Polyplacophora","order":"Neoloricata","habitat":"Low intertidal","description":"Beautiful small chiton (up to 5 cm) with 8 brightly colored shell plates featuring pink, red, or turquoise zigzag lines on cream background.","identificationTips":["8 shell plates with bright pink/red/turquoise zigzag lines","Small size (under 5 cm); cream to pink background","Often on coralline algae, which it feeds on"],"color":"#cc6688"},
  {"commonName":"Veiled Chiton","latinName":"Placiphorella velata","phylum":"Mollusca","class":"Polyplacophora","order":"Neoloricata","habitat":"Low intertidal","description":"A predatory chiton! Uses an enlarged, fleshy head flap ('veil') to trap small crustaceans. Small shell plates surrounded by wide reddish-brown girdle.","identificationTips":["Enlarged, fleshy head flap used like a trap to catch prey","Small shell plates surrounded by wide reddish-brown girdle","The only predatory chiton; found under rocks"],"color":"#8b4513"},
  {"commonName":"Pacific Geoduck","latinName":"Panopea generosa","phylum":"Mollusca","class":"Bivalvia","order":"Adapedonta","habitat":"Low intertidal","description":"Largest burrowing clam in the world (up to 2.5 kg). Massive siphon cannot retract into shell; can extend over 1 m. Lives buried deep in sand. Can live 100+ years.","identificationTips":["Enormous siphon that extends beyond shell and cannot retract","Shell is large, gaping, chalky white","Siphon tip has two holes: one for inhaling, one for exhaling"],"color":"#e8dcc8"},
  {"commonName":"Horse Clam","latinName":"Tresus capax","phylum":"Mollusca","class":"Bivalvia","order":"Veneroida","habitat":"Low intertidal","description":"Very large clam (shell up to 20 cm) with thick, heavy shell and large fused siphons covered in thick wrinkled brown skin. Burrows deep in sand and mud.","identificationTips":["Thick, heavy white shell with dark brown periostracum","Large, wrinkled brown siphons (two fused together)","Shell gapes at siphon end when animal retracts"],"color":"#e0d4bc"},

  # --- More Bivalves & Gastropods --- 164-171
  {"commonName":"Pink Scallop","latinName":"Chlamys hastata","phylum":"Mollusca","class":"Bivalvia","order":"Pectinida","habitat":"Low intertidal","description":"Colorful swimming scallop (up to 8 cm) with pink, orange, or reddish shell and prominent radiating ribs. Often forms mutualistic relationship with encrusting sponge.","identificationTips":["Bright pink to reddish shell with strong radiating ribs","Often has sponge encrusting one valve","Can swim by clapping valves; blue eyes along mantle"],"color":"#cc6688"},
  {"commonName":"Rough Piddock","latinName":"Zirfaea pilsbryi","phylum":"Mollusca","class":"Bivalvia","order":"Myoida","habitat":"Low intertidal","description":"Unusual bivalve that bores into rock and clay using its shell as a rasping tool. Creates permanent burrows it cannot leave. Has distinctive file-like texture on shell front.","identificationTips":["Shell has rough, file-like texture on anterior end for boring","Creates perfectly round holes in rock, clay, or wood","Long fused siphon; shell gapes at both ends"],"color":"#d8c8a8"},
  {"commonName":"Northern Abalone","latinName":"Haliotis kamtschatkana","phylum":"Mollusca","class":"Gastropoda","order":"Lepetellida","habitat":"Low intertidal","description":"Rare and endangered large snail (shell up to 15 cm) with flattened, ear-shaped shell. Exterior mottled red-brown; interior brilliantly iridescent. 3-5 open respiratory holes.","identificationTips":["Large, flattened, ear-shaped shell with 3-5 open holes","Mottled red-brown outside; stunning iridescent inside","Endangered species — harvesting prohibited in BC"],"color":"#aa5544"},
  {"commonName":"Dire Whelk","latinName":"Lirabuccinum dirum","phylum":"Mollusca","class":"Gastropoda","order":"Neogastropoda","habitat":"Mid intertidal","description":"Common predatory snail (up to 6 cm) with thick, ribbed shell and long siphon canal. Dark grey-brown to rusty brown. Feeds on barnacles, mussels, and carrion.","identificationTips":["Thick, ribbed shell with long siphon canal at anterior end","Dark grey to rusty brown shell, often worn apex","Active scavenger and predator on mussel beds"],"color":"#5a4a3a"},
  {"commonName":"Leafy Hornmouth","latinName":"Ceratostoma foliatum","phylum":"Mollusca","class":"Gastropoda","order":"Neogastropoda","habitat":"Mid to low intertidal","description":"Distinctive predatory snail (up to 8 cm) with three prominent, wing-like frilly flanges running down the shell. Creamy white to brown. Drills into barnacles and mussels.","identificationTips":["Three prominent leaf-like or wing-like flanges along the shell","Shell is creamy white to brown with fine spiral ridges","Predatory; drills into barnacles and mussels"],"color":"#c4b090"},
  {"commonName":"Oregon Triton","latinName":"Fusitriton oregonensis","phylum":"Mollusca","class":"Gastropoda","order":"Littorinimorpha","habitat":"Subtidal","description":"One of the largest snails on the Pacific coast (shell up to 15 cm). Covered in fine velvety brown periostracum. White shell underneath with spiral ridges. Predatory.","identificationTips":["Large, spindle-shaped shell covered in velvety brown periostracum","White shell with prominent spiral ridges underneath","Tall spire and long siphon canal; predatory"],"color":"#8b6914"},
  {"commonName":"Keyhole Limpet","latinName":"Diodora aspera","phylum":"Mollusca","class":"Gastropoda","order":"Lepetellida","habitat":"Low intertidal","description":"Limpet-like snail (shell up to 5 cm) with distinctive oval keyhole at the apex of the shell. Coarse radial ribs. Greysh-white with darker rays. Grazes on sponges.","identificationTips":["Distinctive keyhole or slot at apex of shell (not at margin)","Conical, ribbed shell with grey-white coloration and darker rays","Hole at top expels water after filter-feeding"],"color":"#d8ccc0"},

  # --- Crustaceans --- 172-180
  {"commonName":"Dungeness Crab","latinName":"Metacarcinus magister","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Subtidal","description":"The most important commercial crab on the Pacific coast. Broad, oval carapace (up to 25 cm across) with 10 teeth per side. Reddish-brown with white-tipped claws.","identificationTips":["Broad, oval carapace with 10 teeth on each side","Reddish-brown with white-tipped claws","Last pair of legs not flattened (unlike swimming crabs)"],"color":"#b8652a"},
  {"commonName":"Pygmy Rock Crab","latinName":"Cancer oregonensis","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Low intertidal","description":"Small, hairy rock crab (carapace up to 5 cm) with reddish-brown carapace covered in short hairs and granules. Claws have black tips. Found under rocks.","identificationTips":["Small, reddish-brown crab with bumpy granular carapace covered in fine hairs","Black-tipped claws; carapace up to 5 cm wide","Found under rocks; often with encrusting invertebrates"],"color":"#8b5a3a"},
  {"commonName":"Skeleton Shrimp","latinName":"Caprella spp.","phylum":"Arthropoda","class":"Malacostraca","order":"Amphipoda","habitat":"Low intertidal","description":"Bizarre, extremely slender amphipod that looks like a tiny stick insect. Clings to hydroids and algae using specialized rear legs. Moves like an inchworm. Master of camouflage.","identificationTips":["Extremely slender body, looks like a tiny stick or skeleton","Clings to hydroids with specialized grasping rear legs","Moves in inchworm-like motion; sways to mimic substrate"],"color":"#c0b898"},
  {"commonName":"Spider Crab","latinName":"Oregonia gracilis","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Subtidal","description":"Slender, long-legged decorator crab (carapace up to 4 cm) that covers itself with bits of algae and debris. Triangular carapace with two diverging rostral spines.","identificationTips":["Very long, slender legs and triangular carapace with two pointed rostral spines","Almost always decorated with algae, hydroids, and debris","Walks on tiptoes; looks like floating seaweed"],"color":"#8c7a5c"},
  {"commonName":"Blue Mud Shrimp","latinName":"Upogebia pugettensis","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Low intertidal","description":"Large, secretive mud shrimp (up to 15 cm) living in Y-shaped burrows in mudflats. Soft-bodied, bluish-grey. Burrows provide habitat for many commensal species.","identificationTips":["Bluish-grey, soft-bodied shrimp with large flattened abdomen","Lives in deep Y-shaped burrows in mudflats","Siphons water through its burrow; filter-feeds"],"color":"#6688aa"},
  {"commonName":"Ghost Shrimp","latinName":"Neotrypaea californiensis","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Low intertidal","description":"Pale, translucent mud shrimp (up to 10 cm) living in deep burrows in sandy mudflats. Burrows extend up to 1 m deep. Major ecosystem engineer.","identificationTips":["Pale, translucent body; one claw much larger than the other","Lives in deep burrows; creates volcano mounds","Burrows extend up to 1 m; major ecosystem engineer"],"color":"#d8c8b8"},
  {"commonName":"Spot Prawn","latinName":"Pandalus platyceros","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Subtidal","description":"Largest shrimp on the Pacific coast (up to 30 cm). Distinctive white spots on abdominal segments 1 and 5, white bands on antennae. Prized commercial and recreational species.","identificationTips":["Large shrimp with white spots on abdominal segments 1 and 5","White bands on long, sweeping antennae","Reddish-brown body; found in rocky areas"],"color":"#cc6644"},
  {"commonName":"Flat Porcelain Crab","latinName":"Petrolisthes cinctipes","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Mid intertidal","description":"Small, extremely flat crab (carapace up to 2 cm) with large, flat claws. Filter-feeds using feathery mouthparts. Very common under rocks, often stacked in large numbers.","identificationTips":["Extremely flat, disc-like body with large flattened claws","Filter-feeds with long feathery mouthparts","Very common under intertidal rocks; sheds claws easily"],"color":"#a08060"},
  {"commonName":"Puget Sound King Crab","latinName":"Lopholithodes mandtii","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","habitat":"Subtidal","description":"Large, heavily armored crab (carapace up to 25 cm) with spiny, knobby shell. Mottled orange, red, and purple. Looks almost like a bizarre rock. Found on rocky reefs.","identificationTips":["Very large, spiny, heavily armored crab with knobby carapace","Mottled orange, red, and purple — excellent camouflage","Claws are thick and powerful; juveniles bright orange"],"color":"#cc6633"},

  # --- More Echinodermata --- 181-184
  {"commonName":"Slender Sea Star","latinName":"Pisaster giganteus","phylum":"Echinodermata","class":"Asteroidea","order":"Forcipulatida","habitat":"Low intertidal","description":"Large sea star (up to 60 cm) with 5 thick, tapering arms covered in prominent white/blue/purple spines encircled by blue rings. Often in mussel beds.","identificationTips":["5 thick, tapering arms with bold white/blue spines with blue rings","Color ranges from brown to purple to grey","Larger and more robust spines than Ochre Sea Star"],"color":"#7a5090"},
  {"commonName":"Spiny Brittle Star","latinName":"Ophiothrix spiculata","phylum":"Echinodermata","class":"Ophiuroidea","order":"Ophiurida","habitat":"Low intertidal","description":"Colorful brittle star (disk up to 2 cm) with arms covered in fine spines giving a fuzzy appearance. Vivid orange to red disk with pattern. Arms banded in orange, brown, cream.","identificationTips":["Long, slender arms covered in fine spines — looks fuzzy","Vivid orange to red central disk with distinct pattern","Arms have banded patterns of orange, brown, and cream"],"color":"#ee8844"},
  {"commonName":"White Sea Cucumber","latinName":"Eupentacta quinquesemita","phylum":"Echinodermata","class":"Holothuroidea","order":"Dendrochirotida","habitat":"Low intertidal","description":"Small, white to cream sea cucumber (up to 8 cm) with 10 feeding tentacles. Covered in tube feet in 5 rows. Found under rocks; retracts into tight ball when disturbed.","identificationTips":["Small, white to cream body with 10 tentacles (8 large with branching tips, 2 small)","5 rows of tube feet running the length","Common under rocks; retracts into tight ball"],"color":"#f5f0e0"},
  {"commonName":"Sand Dollar","latinName":"Dendraster excentricus","phylum":"Echinodermata","class":"Echinoidea","order":"Clypeasteroida","habitat":"Subtidal","description":"Flattened, disc-shaped urchin (up to 10 cm) with distinctive 5-petaled flower pattern on upper surface. Velvety covering of short spines for burrowing. Tests wash ashore frequently.","identificationTips":["Flattened, disc-shaped test with 5-petaled flower pattern on top","Covered in very short, velvety purple to grey spines","Found buried in sand in dense aggregations"],"color":"#a090b0"},

  # --- More Cnidaria --- 185-190
  {"commonName":"Orange Cup Coral","latinName":"Balanophyllia elegans","phylum":"Cnidaria","class":"Anthozoa","order":"Scleractinia","habitat":"Low intertidal","description":"The only hard stony coral commonly found in Pacific NW intertidal zone. Solitary, bright orange polyp (up to 2 cm) with hard cup-shaped calcareous skeleton.","identificationTips":["Small, solitary, bright orange cup-shaped skeleton with single polyp","Stony skeleton — feels hard and crunchy (unlike anemones)","Found under rocks and in shaded crevices"],"color":"#ff9933"},
  {"commonName":"Pink Hydrocoral","latinName":"Stylaster spp.","phylum":"Cnidaria","class":"Hydrozoa","order":"Anthoathecata","habitat":"Subtidal","description":"Colonial hydroid that secretes hard, branching, pink/purple calcareous skeleton resembling true coral. Tiny pores house feeding polyps. Often encrusted with sponges.","identificationTips":["Hard, branching, pink to purple skeleton — looks like coral but is a hydrozoan","Tiny pores (gastropores) where polyps extend","Subtidal; sometimes washed ashore after storms"],"color":"#cc6699"},
  {"commonName":"By-the-wind Sailor","latinName":"Velella velella","phylum":"Cnidaria","class":"Hydrozoa","order":"Anthoathecata","habitat":"Subtidal","description":"Beautiful free-floating colonial hydroid with small blue oval float and stiff triangular sail. Wind propels it across ocean surface. Thousands wash ashore during spring wind events.","identificationTips":["Small (up to 7 cm), blue, oval float with stiff triangular vertical sail","Underneath float are tiny feeding polyps and stinging tentacles","Often washes ashore in massive numbers during onshore wind events"],"color":"#3366cc"},
  {"commonName":"Lion's Mane Jellyfish","latinName":"Cyanea capillata","phylum":"Cnidaria","class":"Scyphozoa","order":"Semaeostomeae","habitat":"Subtidal","description":"Largest known jellyfish — bell up to 2 m diameter, tentacles trailing up to 30 m. Reddish-brown to yellow bell with 8 lobed clusters of fine hair-like tentacles.","identificationTips":["Very large saucer-shaped bell with 8 thick lobed tentacle clusters","Reddish-brown to yellow bell; hundreds of fine tentacles","Sting is painful but rarely dangerous"],"color":"#cc5533"},
  {"commonName":"Moon Jellyfish","latinName":"Aurelia aurita","phylum":"Cnidaria","class":"Scyphozoa","order":"Semaeostomeae","habitat":"Subtidal","description":"Common translucent jellyfish (bell up to 40 cm) with 4 distinctive purple-pink horseshoe-shaped gonads visible through the bell. Mild sting. Often in huge summer swarms.","identificationTips":["Translucent saucer-shaped bell with 4 purple-pink horseshoe shapes visible inside","Short, fine tentacles around bell margin","Often seen in huge swarms (smacks) in harbors in summer"],"color":"#c8d8e8"},
  {"commonName":"Fried Egg Jellyfish","latinName":"Phacellophora camtschatica","phylum":"Cnidaria","class":"Scyphozoa","order":"Semaeostomeae","habitat":"Subtidal","description":"Large, beautiful jellyfish (bell up to 60 cm) with translucent white bell and distinct yellow-orange central mass — looks like a fried egg! Feeds on other jellyfish.","identificationTips":["Looks like a fried egg: white translucent bell with bright yellow center","16 clusters of long trailing tentacles","Often with small fish and crabs hitching a ride near the bell"],"color":"#ffcc33"},

  # --- Marine Worms --- 191-195
  {"commonName":"Nereid Worm","latinName":"Nereis vexillosa","phylum":"Annelida","class":"Polychaeta","order":"Phyllodocida","habitat":"Mid intertidal","description":"Large, active polychaete (up to 30 cm) with iridescent bluish-green body segments. Well-developed parapodia (paddle-like appendages). Powerful jaws with two black teeth. Agile predator.","identificationTips":["Large, muscular worm with iridescent blue-green coloration","Two rows of paddle-like parapodia along the body","Powerful jaws with two black teeth; active predator in mussel beds"],"color":"#337766"},
  {"commonName":"Blood Worm","latinName":"Glycera spp.","phylum":"Annelida","class":"Polychaeta","order":"Phyllodocida","habitat":"Low intertidal","description":"Burrowing polychaete (up to 20 cm) with pink to red body (hemoglobin) and distinctive eversible proboscis tipped with 4 black venom-injecting jaws. Used as bait by fishermen.","identificationTips":["Bright pink to red body with eversible proboscis tipped by 4 black jaws","Jaws are venomous — can deliver painful bite","Lives buried in sand and mud"],"color":"#cc4455"},
  {"commonName":"Scale Worm","latinName":"Halosydna brevisetosa","phylum":"Annelida","class":"Polychaeta","order":"Phyllodocida","habitat":"Low intertidal","description":"Flattened polychaete (up to 5 cm) with 18 pairs of overlapping, iridescent scales (elytra) covering its back. Scales shimmer in gold, green, and blue. Often commensal with other inverts.","identificationTips":["Flattened body with 18 pairs of overlapping iridescent scales on back","Scales shimmer with gold, green, and blue colors","Found under rocks; often with sea stars or tube worms"],"color":"#a09050"},
  {"commonName":"Ribbon Worm","latinName":"Paranemertes peregrina","phylum":"Nemertea","class":"Anopla","order":"Heteronemertea","habitat":"Low intertidal","description":"Long, slender, unsegmented worm (up to 30 cm) with purple-brown body. Possesses unique eversible proboscis (separate from gut) to capture prey. Can stretch dramatically.","identificationTips":["Slender, unsegmented, purple-brown worm that can stretch dramatically","Eversible proboscis — a long sticky tube shot out to capture prey","Soft, muscular body; glides using cilia"],"color":"#6a3a5a"},
  {"commonName":"Peanut Worm","latinName":"Phascolosoma agassizii","phylum":"Sipuncula","class":"Sipunculidea","order":"Sipunculida","habitat":"Low intertidal","description":"Unusual unsegmented worm (up to 5 cm) with bulbous peanut-shaped body and retractable slender introvert tipped with tentacles. Lives in crevices and empty shells.","identificationTips":["Peanut-shaped body with slender retractable introvert at one end","Tiny branched tentacles at tip of introvert","Found in rock crevices, empty snail shells, kelp holdfasts"],"color":"#b8a060"},

  # --- Miscellaneous Invertebrates --- 196-200
  {"commonName":"Giant Flatworm","latinName":"Kaburakia excelsa","phylum":"Platyhelminthes","class":"Turbellaria","order":"Polycladida","habitat":"Low intertidal","description":"Large, thin, leaf-like flatworm (up to 10 cm) that glides over rocks. Cream to pale brown with network of darker lines. Two sensory tentacles and many eyespots. Predatory.","identificationTips":["Thin, flat, leaf-like body like a crawling piece of wet tissue paper","Two small tentacle-like folds near front; numerous eyespots","Glides smoothly over rocks and algae"],"color":"#d8c8a0"},
  {"commonName":"Glass Sponge","latinName":"Aphrocallistes vastus","phylum":"Porifera","class":"Hexactinellida","order":"Hexactinosida","habitat":"Subtidal","description":"Deep-water sponge (found in shallow BC fjords) with skeleton of fused silica (glass) spicules. Forms structured reefs. Looks like a delicate white or grey vase.","identificationTips":["Rigid, lace-like skeleton made of fused glass spicules","White to pale grey; vase or funnel-shaped","Forms dense reefs; encountered by divers in BC fjords"],"color":"#e8ecef"},
  {"commonName":"Finger Sponge","latinName":"Neoesperiopsis rigida","phylum":"Porifera","class":"Demospongiae","order":"Poecilosclerida","habitat":"Low intertidal","description":"Erect, branching sponge (up to 20 cm) with thick finger-like projections. Orange, yellow, or pale brown. Smooth but firm texture. Common on dock pilings.","identificationTips":["Thick, finger-like branches growing erect from a base","Orange, yellow, or pale brown; smooth but firm texture","Found attached to rocks and docks"],"color":"#ee9944"},
  {"commonName":"Didemnum Tunicate","latinName":"Didemnum vexillum","phylum":"Chordata","class":"Ascidiacea","order":"Aplousobranchia","habitat":"Low intertidal","description":"Invasive colonial tunicate forming extensive, thick, slimy sheets over rocks, docks, and other surfaces. Pale yellow to beige with distinctive porous surface. Major fouling species.","identificationTips":["Thick, slimy, lobed or sheet-like colonies that overgrow everything","Pale yellow to beige with distinctive, porous surface","Highly invasive; forms extensive mats on docks and rocks"],"color":"#d8d8a0"},
  {"commonName":"Orange Sea Pen","latinName":"Ptilosarcus gurneyi","phylum":"Cnidaria","class":"Anthozoa","order":"Pennatulacea","habitat":"Subtidal","description":"Colonial octocoral looking like an orange feather or quill pen. Fleshy stalk anchored in soft sediment. Upper portion has numerous feeding polyps on lateral branches. Bioluminescent!","identificationTips":["Fleshy, orange, feather-like or quill-shaped colony in sand","Central stalk with lateral branches bearing tiny polyps","Bioluminescent — emits green glow when touched"],"color":"#ff8822"},

  # --- More Fish & Chordates --- 201-210
  {"commonName":"Pacific Sand Lance","latinName":"Ammodytes hexapterus","phylum":"Chordata","class":"Actinopterygii","order":"Trachiniformes","habitat":"Subtidal","description":"Slender, silvery schooling fish (up to 25 cm). Has pointed jaw-like lower lip and lacks swim bladder. Burrows into sand to escape. Critical forage fish for seabirds and salmon.","identificationTips":["Very slender, silvery, eel-like body with pointed lower jaw","Schooling fish; forms dense bait balls near shore","Rapidly burrows into sand at the surface"],"color":"#a0b8c0"},
  {"commonName":"Snailfish","latinName":"Liparis florae","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Low intertidal","description":"Small, tadpole-like fish (up to 15 cm) with large rounded head and tapering body. Smooth, scaleless, often translucent skin with ventral sucker disc. Found under rocks in tidepools.","identificationTips":["Tadpole-shaped body with large rounded head and sucker disc on belly","Smooth, scaleless, translucent skin — organs may be visible","Found under rocks; muddy brown to olive with faint spots"],"color":"#a09070"},
  {"commonName":"Bay Pipefish","latinName":"Syngnathus leptorhynchus","phylum":"Chordata","class":"Actinopterygii","order":"Syngnathiformes","habitat":"Subtidal","description":"Slender fish (up to 35 cm) related to seahorses. Long tubular snout and armored body of bony rings. Green to brown, perfectly mimicking eelgrass blades. Male carries eggs in brood pouch.","identificationTips":["Extremely slender, eel-like body with long tubular snout like a seahorse","Body covered in bony rings instead of scales","Green to brown; floats in eelgrass beds"],"color":"#668844"},
  {"commonName":"Colonial Tunicate (Star Ascidian)","latinName":"Botryllus schlosseri","phylum":"Chordata","class":"Ascidiacea","order":"Stolidobranchia","habitat":"Low intertidal","description":"Beautiful invasive colonial tunicate forming flat sheets with zooids in star-shaped or flower-like clusters. Each star has several zooids sharing a central excurrent siphon. Highly variable color.","identificationTips":["Flat, thin sheets with zooids in distinctive star or flower-like patterns","Each star cluster has a central opening surrounded by zooids","Color ranges from orange to purple, green, or brown"],"color":"#cc8833"},
  {"commonName":"Kelp Isopod","latinName":"Idotea wosnesenskii","phylum":"Arthropoda","class":"Malacostraca","order":"Isopoda","habitat":"Low intertidal","description":"Large isopod (up to 4 cm) that lives on kelp and seaweeds. Well-camouflaged, elongated, flattened body matches the color of the algae it lives on. Grazes on kelp tissue.","identificationTips":["Large, elongated, flattened isopod; body matches kelp color","Has a telson (tail plate) with a pointed tip","Common on kelp blades; olive, brown, or green"],"color":"#6b8a3a"},

  # --- Seaweeds & Seagrasses --- 206-213
  {"commonName":"Pelagic Gooseneck Barnacle","latinName":"Lepas anatifera","phylum":"Arthropoda","class":"Thecostraca","order":"Scalpelliformes","habitat":"Subtidal","description":"Stalked barnacle attaching to floating objects in the open ocean. Long, flexible stalk topped with cluster of white triangular plates. Often found on driftwood and buoys.","identificationTips":["Smooth flexible stalk topped with cluster of white triangular plates","Attaches to floating objects — not intertidal rocks","Shell plates white with bluish tinge; stalk grey-black"],"color":"#b0b8c0"},
  {"commonName":"Encrusting Bryozoan","latinName":"Schizoporella japonica","phylum":"Bryozoa","class":"Gymnolaemata","order":"Cheilostomatida","habitat":"Low intertidal","description":"Invasive encrusting bryozoan forming thick orange to pinkish crusts on rocks, docks, and shells. Bumpy surface with numerous tiny pores. Can overgrow and smother other organisms.","identificationTips":["Thick, bumpy, orange to pinkish encrusting patches on hard surfaces","Surface covered in tiny rectangular pores (each housing a zooid)","Often on docks, boat hulls, and rocks; introduced from Japan"],"color":"#cc7744"},
  {"commonName":"Surfgrass","latinName":"Phyllospadix scouleri","phylum":"Tracheophyta","class":"Monocots","order":"Alismatales","habitat":"Low intertidal","description":"One of the few true flowering plants (not an alga!) in the marine intertidal. Forms dense, bright green meadows on wave-exposed rocks. Long, narrow, tough leaves. Critical nursery habitat.","identificationTips":["Long, narrow, bright green leaves growing in dense clumps","Rooted in sand or rock crevices on wave-exposed shores","A true flowering plant — not a seaweed! Produces tiny underwater flowers"],"color":"#44aa33"},
  {"commonName":"Eelgrass","latinName":"Zostera marina","phylum":"Tracheophyta","class":"Monocots","order":"Alismatales","habitat":"Subtidal","description":"True flowering seagrass forming extensive underwater meadows in soft sediment. Long, ribbon-like bright green leaves up to 1 m. Ecologically critical habitat for fish, crabs, and waterfowl.","identificationTips":["Long, flat, ribbon-like green leaves up to 1 m long","Grows in soft sediment in sheltered bays and estuaries","Forms dense underwater meadows; vital nursery habitat"],"color":"#55bb44"},
  {"commonName":"Feather Boa Kelp","latinName":"Egregia menziesii","phylum":"Ochrophyta","class":"Phaeophyceae","order":"Laminariales","habitat":"Low intertidal","description":"Large, distinctive brown alga (up to 5 m) with thick, flat main stipe covered in numerous small lateral blades and floats. Looks like a feather boa. Very common on rocky shores.","identificationTips":["Thick, flat, strap-like main axis covered with small blades and floats","Olive brown to dark brown; up to 5 m long","Looks like a feather boa; habitat for many small invertebrates"],"color":"#5a6b2a"},
  {"commonName":"Sea Sac","latinName":"Halosaccion glandiforme","phylum":"Rhodophyta","class":"Florideophyceae","order":"Palmariales","habitat":"Mid intertidal","description":"Unique red alga forming hollow, fluid-filled, elongated sacs. Golden-brown to olive. Grows in clusters on rocks. When squeezed, the sac squirts water!","identificationTips":["Hollow, elongated, sausage-shaped sacs filled with seawater","Golden-brown to olive; grows in dense clusters","Squirts water when squeezed; mid-intertidal"],"color":"#aa8844"},

  # --- Additional Fish --- 213-225
  {"commonName":"Quillback Rockfish","latinName":"Sebastes maliger","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Rockfish (up to 60 cm) with distinctive high, quill-like dorsal fin (taller in front). Brown to orange-brown with white or yellow blotches. Often near crevices.","identificationTips":["Extremely tall, quill-like dorsal fin spines (front spines longest)","Brown to orange-brown body with white or yellow blotches","Prefers rocky reefs near crevices and caves"],"color":"#996633"},
  {"commonName":"Tiger Rockfish","latinName":"Sebastes nigrocinctus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Stunning rockfish (up to 60 cm) with bold 5-6 dark red to black vertical bars on pink to white body — like tiger stripes. Lives in rocky crevices. Can live 116+ years!","identificationTips":["Bold dark vertical bands (5-6) on pink to white body — tiger stripes","Large, robust body with prominent head spines","Lives in rocky crevices; may live over 100 years"],"color":"#cc4455"},
  {"commonName":"Canary Rockfish","latinName":"Sebastes pinniger","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Bright orange to yellow rockfish (up to 75 cm) with distinctive pale grey-white lateral line and 3 orange stripes across the head. Often hovers above the bottom near rocky reefs.","identificationTips":["Bright orange to yellow body with prominent grey-white lateral line","3 orange stripes radiating across head and gill cover","Large bright eyes; often hovers above the bottom"],"color":"#ee8833"},
  {"commonName":"Pacific Staghorn Sculpin","latinName":"Leptocottus armatus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Low intertidal","description":"Medium sculpin (up to 30 cm) with prominent antler-like cheek spine. Mottled brown and grey. Very common in estuaries and tidepools. Tolerates wide range of salinities.","identificationTips":["Prominent upward-curving cheek spine that looks like antler","Large flattened head with wide frowning mouth","Mottled brown-grey; abundant in estuaries"],"color":"#8b7355"},
  {"commonName":"Sailfin Sculpin","latinName":"Nautichthys oculofasciatus","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","habitat":"Subtidal","description":"Bizarre-looking sculpin (up to 20 cm) with enormously tall, sail-like first dorsal fin. Dark band across eye. Unlike most sculpins, it actively swims in the water column.","identificationTips":["Enormous, sail-like first dorsal fin (can be raised like a sail)","Dark band through the eye; long slender body","Often actively swims above the bottom (unusual for sculpins)"],"color":"#888899"},
  {"commonName":"Pacific Sardine","latinName":"Sardinops sagax","phylum":"Chordata","class":"Actinopterygii","order":"Clupeiformes","habitat":"Subtidal","description":"Small, silvery schooling fish (up to 40 cm) with row of dark spots along side and blue-green back. Forms massive schools. Critical food for seabirds, mammals, and larger fish.","identificationTips":["Silvery body with row of dark spots along upper flank","Blue-green back; deeply forked tail","Forms huge dense schools; often near surface in summer"],"color":"#8899aa"},
  {"commonName":"Plainfin Midshipman","latinName":"Porichthys notatus","phylum":"Chordata","class":"Actinopterygii","order":"Batrachoidiformes","habitat":"Low intertidal","description":"Bizarre fish (up to 38 cm) with rows of glowing photophores (light-emitting organs) along its sides. Males produce loud humming sound during breeding season. Hides under rocks during the day.","identificationTips":["Rows of small glowing photophores like button lights along body","Large broad head with wide mouth; olive brown to purple","Males produce loud humming (singing fish) in summer"],"color":"#5a4a5a"},
  {"commonName":"Bay Goby","latinName":"Lepidogobius lepidus","phylum":"Chordata","class":"Actinopterygii","order":"Gobiiformes","habitat":"Subtidal","description":"Small, slender goby (up to 15 cm) with large mouth and eyes high on the head. Pelvic fins fused into suction disc. Pale olive to tan with faint darker spots.","identificationTips":["Slender body with fused pelvic fins forming suction disc on belly","Eyes positioned high on head; large slightly upturned mouth","Pale tan to olive; rests on bottom near burrows"],"color":"#a09070"},
  {"commonName":"Blackeye Goby","latinName":"Rhinogobiops nicholsii","phylum":"Chordata","class":"Actinopterygii","order":"Gobiiformes","habitat":"Subtidal","description":"Small, pale goby (up to 15 cm) with distinctive large black spot on first dorsal fin. Cream to pale blue-grey body with faint orange speckles. Males guard eggs in burrows.","identificationTips":["Large black spot on first dorsal fin (looks like an eye)","Cream to pale blue-grey body with faint orange spots","Makes small burrows in sand near rocks"],"color":"#ccbb99"},
  {"commonName":"Pink Surfperch","latinName":"Zalembius rosaceus","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","habitat":"Subtidal","description":"Small, rosy-pink surfperch (up to 20 cm) with deep compressed body and dark blotch on dorsal fin. Often in small schools over sandy areas near reefs.","identificationTips":["Rosy-pink to reddish body with dark blotch on dorsal fin","Deep compressed body with forked tail","Often in small schools over sandy areas"],"color":"#cc8899"},
  {"commonName":"English Sole","latinName":"Parophrys vetulus","phylum":"Chordata","class":"Actinopterygii","order":"Pleuronectiformes","habitat":"Subtidal","description":"Right-eyed flatfish (eyes on right side) with slender oval body. Mottled brown upper surface with nearly straight lateral line. Common in sandy/muddy bays. Important commercial species.","identificationTips":["Right-eyed flatfish (both eyes on right side) with oval slender body","Mottled brown upper surface with nearly straight lateral line","Common in sandy and muddy substrate in protected bays"],"color":"#8b7a5a"},
  {"commonName":"Spiny Dogfish","latinName":"Squalus acanthias","phylum":"Chordata","class":"Chondrichthyes","order":"Squaliformes","habitat":"Subtidal","description":"Small shark (up to 1.5 m) with slender grey body covered in small white spots. Venomous spine in front of each dorsal fin. Swims in large schools. One of the most common temperate sharks.","identificationTips":["Slender grey shark with small white spots on the sides","Venomous spine in front of each dorsal fin","Schooling behavior; no anal fin; feeds on small fish and squid"],"color":"#667788"},
]

def main():
    # 1. Read data.js
    with open(DATA_JS, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Strip trailing ] and ; and blank lines after
    end = content.rfind('];')
    if end == -1:
        print("ERROR: Could not find ]; in data.js")
        return
    # Keep everything up to and including the last entry
    content = content[:end].rstrip()
    
    # 2. Append new species
    next_id = 126
    for i, sp in enumerate(NEW_SPECIES):
        content += f"""
  {{
    id: {next_id + i},
    commonName: "{sp['commonName']}",
    latinName: "{sp['latinName']}",
    phylum: "{sp['phylum']}",
    class: "{sp['class']}",
    order: "{sp['order']}",
    habitat: "{sp['habitat']}",
    description: "{sp['description']}",
    identificationTips: [{', '.join(f'"{t}"' for t in sp['identificationTips'])}],
    imageUrl: "images/species-{next_id + i:03d}.jpg" if {next_id + i} >= 100 else "images/species-{next_id + i:02d}.jpg",
    imageCredit: "Photo: Wikimedia Commons CC-BY-SA",
    color: "{sp['color']}"
  }}"""
        if i < len(NEW_SPECIES) - 1:
            content += ","
    
    content += "\n];"
    
    # Fix imageUrls: 3-digit for 100+
    for i in range(126, 226):
        if i >= 100:
            content = content.replace(f'"images/species-{i:02d}.jpg"', f'"images/species-{i:03d}.jpg"')
    
    with open(DATA_JS, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Appended {len(NEW_SPECIES)} new species to data.js (IDs 126-{125+len(NEW_SPECIES)})")
    
    # 3. Create placeholder images
    os.makedirs(IMAGES_DIR, exist_ok=True)
    
    # Minimal valid JPEG (1x1 pixel)
    import struct
    def create_minimal_jpg(filename):
        # Smallest possible valid JPEG (from Wikipedia magic bytes example)
        jpg_data = bytes.fromhex(
            "FFD8FFE000104A46494600010101006000600000FFDB00430001010101"
            "0101010101010101010101010101010101010101010101010101010101"
            "0101010101010101010101010101010101010101010101010101010101"
            "FFDB004301010101010101010101010101010101010101010101010101"
            "0101010101010101010101010101010101010101010101010101010101"
            "0101010101010101010101FFC000110800010001030122000211010311"
            "01FFC4001410000000000000000000000000000000000FFC40014100100"
            "00000000000000000000000000000000FFDA000C03010002110311003F"
            "00245C94FFD9"
        )
        with open(filename, 'wb') as f:
            f.write(jpg_data)
    
    created = 0
    for i in range(126, 226):
        fn = os.path.join(IMAGES_DIR, f'species-{i:03d}.jpg')
        if not os.path.exists(fn):
            create_minimal_jpg(fn)
            created += 1
    
    print(f"Created {created} placeholder images")
    
    # 4. Update index.html metadata
    index_html = os.path.join(BASE, 'index.html')
    with open(index_html, 'r', encoding='utf-8') as f:
        html = f.read()
    html = html.replace('125 intertidal', '225 intertidal')
    html = html.replace('125 species', '225 species')
    html = html.replace('125 intertidal, subtidal, & nearshore fish species', '225 intertidal, subtidal, & nearshore species')
    with open(index_html, 'w', encoding='utf-8') as f:
        f.write(html)
    print("Updated index.html: 125 → 225")
    
    # 5. Update library.js search placeholder
    library_js = os.path.join(BASE, 'js', 'library.js')
    with open(library_js, 'r', encoding='utf-8') as f:
        lib = f.read()
    lib = lib.replace('Search 125 species', 'Search 225 species')
    with open(library_js, 'w', encoding='utf-8') as f:
        f.write(lib)
    print("Updated library.js:")
    
    print("\nDone! New species IDs: 126-225")

if __name__ == '__main__':
    main()